spaces
Change-Id: I85696ebf0cd12dd0c5f7de741e64388c9cd33ea5

diff --git a/bin/post-tag-hook b/bin/post-tag-hook
--- a/bin/post-tag-hook
+++ b/bin/post-tag-hook
@@ -1,20 +1,21 @@
 #! /bin/bash -eu
 
+# Git-push to ...$CENTRALREPO
+
 # This can be run manually inside the (git) source tree.
-# push to ...$CENTRALREPO
 
 
 if [ ${CENTRALREPO-x} = x ];
 then
     if git remote show | grep origin; then
-	CENTRALREPO=origin;
+        CENTRALREPO=origin;
     elif git remote show | grep maruska; then
-	CENTRALREPO=maruska;
+        CENTRALREPO=maruska;
     else
-	# only 1 line?
-	# don't fail for this?  Or should fail?
-	echo "no central repository defined, so cannot push anywhere" >&2
-	exit 1;
+        # only 1 line?
+        # don't fail for this?  Or should fail?
+        echo "no central repository defined, so cannot push anywhere" >&2
+        exit 1;
     fi
 fi
 
