post-tag-hook: exit with error message.
Change-Id: Idf2949fc09fab097127e11e5189408d4928e4f3f

diff --git a/bin/post-tag-hook b/bin/post-tag-hook
--- a/bin/post-tag-hook
+++ b/bin/post-tag-hook
@@ -13,6 +13,7 @@ then
     else
 	# only 1 line?
 	# don't fail for this?  Or should fail?
+	echo "no central repository defined, so cannot push anywhere" >&2
 	exit 1;
     fi
 fi
