Try to detect which Git remote to push into (after tagging)
Change-Id: Ia7c6ab77fe80950bb68b3f05ef139410f553cbb5

diff --git a/bin/post-tag-hook b/bin/post-tag-hook
--- a/bin/post-tag-hook
+++ b/bin/post-tag-hook
@@ -1,6 +1,23 @@
 #! /bin/bash -eu
 
-: ${CENTRALREPO=origin}
+# This can be run manually inside the (git) source tree.
+
+
+
+if [ ${CENTRALREPO-x} = x ];
+then
+    if git remote show | grep origin; then
+	CENTRALREPO=origin;
+    elif git remote show | grep maruska; then
+	CENTRALREPO=maruska;
+    else
+	# only 1 line?
+	# don't fail for this?  Or should fail?
+	exit 1;
+    fi
+fi
+
+# : ${CENTRALREPO=origin}
 
 : ${GBP_TAG=$(git describe)}
 : ${GBP_BRANCH=$(git name-rev --name-only  HEAD)}
